### ISSUE TITLE
Container not starting on docker. 

### ISSUE THREAD

**Issue by anoopl** [sashimi3/web-socket-test#2]
docker run -p 8010:8010 --name web-socket-test ksdn117/web-socket-test

```npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

+ ws@7.0.0
added 2 packages in 3.529s
npm info ok
Server started
/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/ws/index.js:3:19)```

**Comment by anoopl** [comment]
I cloned the repo and did a docker build and with the new image created so, it's all working good
Please close the issue
